// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pvhxnvwrnlxrnzdjsczh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB2aHhudndybmx4cm56ZGpzY3poIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2MjEzMjAsImV4cCI6MjA2ODE5NzMyMH0.9-if-II3TfTd0U1SelQT8n783VY2_w-RIjfePtnfxcA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});